### PR TITLE
Improve Support for WASM

### PR DESCRIPTION
**Pull request by ashutoshvarma**
## **Motivation**
Use Spartan in WASM environment (browser or WASM runtimes, `wasm32-unknown-unknown`). 
Ref #54

## **Things changed**
- [x] move dependencies `std` features behind new feature `std` (a58ddef8a0377ee7f97ca62c2fbb1a553d68fff9)
Previously there was no way to disable the std features if someone wants to build it in `no_std` or partial std target. Now the same can be done by simply disabling the default feature.
- [x] remove `rand_core` dependency as `rand` re-exports it.
- [x] use `XofReader` instead of `io::Read` for no_std compatibility (f63812b35961d8602b3d0660f269675ee7ac57d4)
- [x] only build bench & profile if std in enabled (074db25ad280c33dbdc503b0625ae14e2661704c)
- [x] add CI job to test builds with default-features disabled. (5169cf208bd5aad58c615c53d59e0835bc158ff3)
- [x] add WASM Support section in readme 

### **How to use Spartan in `wasm32-unknown-unknown`?**
When adding Spartan to `wasm-bindgen` projects or any project that target `wasm32-unknown-unknown`, simply disable the default features and add `getrandom`(v0.1) as a dependency with `wasm-bindgen` feature enabled.

```toml
[dependencies]
spartan = { version = "0.7", default-features = false }
# since spartan uses getrandom(rand's OsRng), we need to enable 'wasm-bindgen'
# feature to make it feed rand seed from js/nodejs env
# https://docs.rs/getrandom/0.1.16/getrandom/index.html#support-for-webassembly-and-asmjs
getrandom = { version = "0.1", features = ["wasm-bindgen"] }
```

### Details for `getrandom`
Spartan uses [`rand` v0.7](https://crates.io/crates/rand/0.7.3/dependencies) (Why not latest rand v0.8? because `curve25519-dalek` v3's `Scalar::random` will break as it uses rand v0.7).
The `rand::rngs::OsRng` depends upon `getrandom` (v0.1) crate which silently fails in `wasm32-unknown-unknown` during runtime, see the discussion https://github.com/rust-random/getrandom/issues/87#issuecomment-522138650  unless `wasm-bindgen` feature is enabled.

### CODE REVIEW

**Comment by ashutoshvarma** [comment]
@microsoft-github-policy-service agree

**Comment by srinathsetty** [comment]
@ashutoshvarma thanks for the PR! It looks great!

From the CI, it looks like there is a minor issue. I don't seem to have the write access to fix this in the PR branch. Can you add a commit to fix this?

error: this `impl` can be derived
  --> src/errors.rs:26:1
   |
26 | / impl Default for ProofVerifyError {
27 | |   fn default() -> Self {
28 | |     ProofVerifyError::InternalError
29 | |   }
30 | | }
   | |_^
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derivable_impls
   = note: `-D clippy::derivable-impls` implied by `-D warnings`
   = help: remove the manual implementation...
help: ...and instead derive it...
   |
7  | #[derive(Default)]
   |
help: ...and mark the default variant
   |
8  ~   #[default]
9  ~   InternalError,
   |

**Comment by ashutoshvarma** [comment]
>  I don't seem to have the write access to fix this in the PR branch.

That's weird, "_Allow edits and access to secrets by maintainers_" checkbox is checked for this PR.

> Can you add a commit to fix this?

Sure.

**Comment by ashutoshvarma** [comment]
@srinathsetty fix pushed!

**Pull request merged**
